pipeline {
    agent any
    options { buildDiscarder(logRotator(numToKeepStr: '1')) 
            }
    stages {
        stage('build') {
            steps {
                script{
                    sh 'ls -l'
                }    
            }
        }
    }
}
